# Generated by Django 4.0.6 on 2022-07-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
