# Generated by Django 4.0.6 on 2022-07-14 04:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blogging', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
